module.exports = {
  VERIFY_USERTWO_COLUMN: 'VERIFY_USERTWO_COLUMN',
  REQUEST_BATTLE: 'REQUEST_BATTLE',
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SEND: 'MESSAGE_SEND',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  USERTWO_COLUMN_STATUS: 'USERTWO_COLUMN_STATUS',
  LOGOUT: 'LOGOUT',
  USER_CREATED: 'USER_CREATED'
};
